### PR TITLE
Acquire borrow mut

### PR DESCRIPTION
**Pull request by juchiast**
Working on #6

### CODE REVIEW

**Comment by realcr** [comment]
@juchiast : May the code be with you!

**Comment by juchiast** [comment]
@realcr 

I decided to keep both `acquire` and `acquire_borrow` in the crate.

You suggested using `Option` and `Option::take` in case user need to take ownership. In `cswitch`, `service_client` need to take the resource and then return it back again, using `Option` here would be ugly and complicated. So I decide to keep the old `acquire` in the code.

Polling `acquire_borrow` is the same as `acquire`, except that the resource will be available immediately after calling `f(&mut t)`. The resource is taken out and sent via `oneshot` just like before, but now it invisible to the user. This is the simplest design I could come up with.

Currently there is code dupplication, I tried to use trait and generic to avoid that but it's hard and complex.

I still keep the `async_borrow` module around. When you want to merge I will remove it.

**Comment by realcr** [comment]
@juchiast : Hi, you are very fast, I just woke up!
The idea with:
```rust
pub struct Move;
pub struct Borrow;
```
is really cool. I didn't think about having both acquire and acquire_borrow in the same crate. 
One thing I believe that we lose with this design is that:
```rust
impl<T, F, B, G, E, O> Future for AcquireFuture<T, F, G, Borrow>
```
has a complicated implementation, this is due to the shared state with `AcquireFuture<T,F,G,Move>`.
In the Borrow case the state `ResourceState::Broken` can never happen (because `f` never takes ownership of the resource), but we still have to deal with this case because the resource could have been broken during a call to the method `acquire_mutex`.

My original intent was to implement something like you began at `acquire_borrow.rs`, having only the `Borrow` implementation. I think that it could have a very small interface and much shorter code.

> You suggested using Option and Option::take in case user need to take ownership. In cswitch, service_client need to take the resource and then return it back again, using Option here would be ugly and complicated. So I decide to keep the old acquire in the code.

I thought about it for a while. I agree that it will be more hassle for the user of the async_mutex to use Option<> if he wants to take ownership. On the other hand, the failures that could happen are due to the function `f`, which is written by the user of async_mutex, so I think it is reasonable to let him deal with the errors that occur - For example: the possible loss of the resource.

My idea is that we keep the implementation of `AsyncMutex` that you have just wrote, as it is indeed very cool (Having both `acquire()` and `acquire_borrow()` methods)  but also try to write a basic implementation of `acquire_borrow.rs`, at least to see what it looks like. What do you think?

**Comment by realcr** [comment]
@juchiast : If you want we can merge this PR and keep the work on `accquire_borrow.rs` on a different PR. It's up to you.

**Review by realcr — APPROVED** [review]

**Comment by juchiast** [comment]
@realcr I'll do in a new PR

**Pull request merged**
